name: Validate TEI documents

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "tei/*.xml"

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate TEI files
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Validate against TEI-All
        uses: dracor-org/tei-validate-action@3229a64b94e940844bbd5721bf5a272f529a34bc # v2.0.0-rc.1
      - name: Validate against DraCor
        uses: dracor-org/tei-validate-action@3229a64b94e940844bbd5721bf5a272f529a34bc # v2.0.0-rc.1
        with:
          schema: dracor
          fatal: no
