name: Validate TEI documents

on:
  workflow_dispatch:
  push:
    paths:
      - "tei/*.xml"

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate TEI documents against TEI_all schema
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Validate
        uses: dracor-org/tei-validate-action@v1.0.0
