name: Validate TEI documents

on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - "tei/*.xml"

jobs:
  validate_tei:
    runs-on: ubuntu-latest
    name: Validate TEI files
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate against TEI-All
        uses: dracor-org/dracor-validate-action@af4da4ae142f2ba85df988af22588220c9759617
      - name: Validate against DraCor
        uses: dracor-org/dracor-validate-action@af4da4ae142f2ba85df988af22588220c9759617
        with:
          schema: dracor
          warn-only: yes
